package list;

import java.io.IOException;

/**
 * A command object that is generated by a parser.
 * Objects implementing ICommand can execute itself by the help
 * of task manager.
 * 
 * @author andhieka, michael
 *
 */
interface ICommand {
    @Deprecated
	@SuppressWarnings("serial")
    class InvalidTaskNumberException extends Exception { };
		
	@SuppressWarnings("serial")
    class CommandExecutionException extends Exception {
	    public CommandExecutionException(String message) {
	        super(message);
	    }
	};
	
	/**
	 * Executes this command.
	 * 
	 * @return the response to be shown in the console.
	 * @throws CommandExecutionException 
	 * @throws InvalidTaskNumberException 
	 * @throws IOException  
	 */
	String execute() throws CommandExecutionException, 
			IOException, InvalidTaskNumberException;
	
	
	/**
	 * Returns the ICommand object necessary to undo the operation.
	 * @return ICommand
	 */
	ICommand getInverseCommand();
	
}
