package list;

/**
 * A command object that is generated by a parser.
 * Objects implementing ICommand can execute itself by the help
 * of task manager.
 * 
 * @author andhieka, michael
 *
 */
interface ICommand {	
	@SuppressWarnings("serial")
    class InvalidTaskNumberException extends Exception { };
		
	@SuppressWarnings("serial")
    class CommandExecutionException extends Exception {
	    public CommandExecutionException(String message) {
	        super(message);
	    }
	};
	
	/**
	 * Executes this command.
	 * 
	 * @return the response to be shown in the console.
	 * @throws InvalidTaskNumberException 
	 */
	String execute() throws InvalidTaskNumberException, CommandExecutionException;
	
	
	/**
	 * Returns the ICommand object necessary to undo the operation.
	 * @return ICommand
	 */
	//ICommand getInverseCommand();
	
}
